### ISSUE TITLE
Function to Mutate a subset of dataset, and reattach it to the dataset

### ISSUE THREAD

**Issue by oobianom** [oobianom/quickcode#27]
Hi Brice, does such a function already exist?

Basically, with dplyr, I can filter and then do all downstream processes like group_by  mutate and so on. But there I need that filtered portion to remain in the entire dataset after the manipulation of that subset.

Let me know if you understand. Else, I can rephrase.

**Comment by brichard1638** [comment]
I believe I understand what you are asking but if you could rephrase your inquiry with a sample dataset, it would be more helpful.

**Comment by oobianom** [comment]
**To make it easier for you to assess, i put together a rough draft of the function and updated this repository.**

Here is an example,
dt = mtcars
# I want to subset to "mpg == 21.0 & cyl == 6", then mutate various columns within that subset while leaving the others intact
# with base R, this is how I would approach it
dt[dt$mpg == 21.0 & dt$cyl == 6,]$cyl = 1000
dt[dt$mpg == 21.0 & dt$cyl == 6,]$hp = 2000
dt[dt$mpg == 21.0 & dt$cyl == 6,]$vs = dt[dt$mpg == 21.0 & dt$cyl == 6,]$hp*2

#with the new function, this how I will do it
mutate_filter(dt,mpg == 21.0 & cyl == 6, cyl=1000,hp=2000,vs=hp*2)

**Comment by brichard1638** [comment]
Given the additional information you have provided, I have crafted what I believe is a function that meets the requirements you have laid out.

**FUNCTION NAME:**
mutate_filter

**TOTAL NUMBER OF FUNCTION ARGUMENTS:**
6

**ARGUMENT NAMES:**
- data
- f_arg1
- f_arg2
- mutcolx
- mutcoly
- expr

**ARGUMENT SUMMARY DESCRIPTION:**
- data: The data frame object to be passed for mutation processing
- f_arg1: The first of two arguments used to filter the data frame passed as data
- f_arg2: A secondary filtering argument
- mutcolx: A target variable in the data frame against which to mutate
- mutcoly: A secondary variable in the data frame against which to mutate
- expr: A mathematical expression extended among two or more variables that produce a new calculated variable called 'calc_fld'

**OPTIONALITY:**
Only two arguments are required to execute the function. These arguments are data and f_arg1.

**FUNCTION STRUCTURE:**
`mutate_filter <- function(data, f_arg1, f_arg2, mutcolx, mutcoly, expr) {`
  `if (missing(f_arg2)) {`
    `d1 <- dplyr::filter(data, eval(parse(text = f_arg1)))`
  `} else {`
    `d1 <- dplyr::filter(data, eval(parse(text = f_arg1)), eval(parse(text = f_arg2)))`
  `}`

  `if (missing(mutcolx)) {`
    `quote(expr = )`
  `} else {`
    `eval(parse(text = paste0("d1$", mutcolx)))`
  `}`
  
  `if (missing(mutcoly)) {`
    `quote(expr = )`
  `} else {`
    `eval(parse(text = paste0("d1$", mutcoly)))`
  `}`
  
  `if (missing(expr)) {`
    `quote(expr = )`
  `} else {`
    `# Evaluate the expression within the data frame context`
    `calc_fld <- eval(parse(text = expr), envir = d1)`
    `# Add the new field to the data frame`
    `d1$calc_fld <- calc_fld`
  `}`
  `return(d1)`
`}`

**FUNCTION TESTING STATUS:**
The function has been tested but not extensively. If the function meets the expectations provided by the previous explanation and requirements as outlined in this issue, additional testing should be conducted.

If the function does not work as provided, especially consistent with the examples provided, please reach out and I will send the function syntax again. It is possible that the conversion from the R application to this medium did not capture the code syntax correctly.

**FUNCTIONAL UTILITY:**
It is not understood what the value proposition is for the arguments in the function called **mutcolx** and **mutcoly**.  Consistent with the requirements provided, they were included. However, mutating an entire data field with a single value does not seem to be useful or provide a high level of utility. Adding a second argument that replicates this functionality is also questionable. Unless a compelling reason exists for the inclusion of these arguments, it is strongly recommended that they be removed from the function. The function would then contain a total of (4) arguments, collectively providing what is believed to be an extraordinary value proposition.

One way to improve the utility of the **mutate_filter** function would be to replace one of the mutcol arguments with an argument that can control the removal of contiguous or non-contiguous variables from the data frame object in the mutated output.

**CODE EXAMPLES:**
`library(DescTools)`
`data("d.pizza")`

`data("mtcars")`
`data("quakes")`

`mutate_filter(mtcars, f_arg1 = "mpg == 21.0", f_arg2 = "cyl == 6", mutcolx = "cyl = 1000", mutcoly = "hp = 2000", expr = "hp*2")`
`mutate_filter(d.pizza[,1:10], f_arg1 = "driver == 'Taylor'", f_arg2 = "area == 'Camden'", expr = "count*price")`
`mutate_filter(mtcars, f_arg1 = "cyl == 8", expr = "vs+am+gear+carb")`
`mutate_filter(quakes, f_arg1 = "stations == 10", expr = "round(mag/depth,3)")`

**Comment by oobianom** [comment]
Thanks Brice. Actually, I don't think we need the secondary arguments since one can easily combine such as "mpg == 21 & cyc == <3"

**Comment by brichard1638** [comment]
Does the proposed function I provided meet the requirements you laid out?
________________________________

**Comment by brichard1638** [comment]
Based on your latest feedback, I've re-constructed the **mutate_filter** function in the following ways:
- Removed both the **mutcolx** and **mutcolx** arguments
- Added a **rem** argument which is designed to remove variables from the passed data frame

**NEW FUNCTION STRUCTURE:**
`mutate_filter <- function(data, f_arg1, f_arg2, rem, expr) {`
  `if (missing(f_arg2)) {`
    `d1 <- dplyr::filter(data, eval(parse(text = f_arg1)))`
  `} else {`
    `d1 <- dplyr::filter(data, eval(parse(text = f_arg1)), eval(parse(text = f_arg2)))`
  `}`
  
  `if (missing(rem)) {`
    `quote(expr = )`
  `} else {`
    `eval(parse(text = paste0("d1 = ", "d1[", "-c(", rem, ")]")))`
  `}`
  
  `if (missing(expr)) {`
    `quote(expr = )`
  `} else {`
    `# Evaluate the expression within the data frame context`
    `calc_fld <- eval(parse(text = expr), envir = d1)`
    `# Add the new field to the data frame`
    `d1$calc_fld <- calc_fld`
  `}`
  `return(d1)`
`}`

It is believed that this version of the **mutate_filter** function possesses a much higher value proposition than its predecessor. As a result, this modified function should be the one selected for inclusion in the **quickcode** package.

**FUNCTION TESTING STATUS:**
The updated function has been tested but not extensively. If the functional output meets the expectations of the requirements previously outlined in this issue, additional testing should be conducted.

**ADDITIONAL NOTES:**
- The **rem** argument does not accept field name string literals
- The **rem** argument maintains a specific encoding syntax that must be observed or the function will crash
- The **rem** argument is encoded using numeric values as a string
- Encoding syntax for the **rem** function for a contiguous removal of variables: "4,5,6" where 4 is the fourth variable in the dataset counting from left-to-right starting with 1
- Encoding syntax for the **rem** function for a non-contiguous removal of variables: "3, 6:9, 15" presuming the passed dataset contains at least 15 variables
- Sorting was thought to be another interesting addition to be added to this function; however, upon testing, it was concluded that sorting by a targeted variable became excessively confusing when the **rem** argument was used in conjunction with a sort. In some instances, depending on the variables to be removed, sorting by a variable ended up returning an error because the sort required passing a variable (by numeric value) that existed AFTER the variables in the **rem** argument were removed. For example, sorting by variable 6 would, at the very worst, crash the algorithm if, subsequent to a removal of variables, there was no variable 6 in the mutated dataset but it existed in the original dataset. Alternatively, in the best case, due to a reshuffling of variable numbers after variable removal, the variable to be sorted would be the incorrect variable sorted.

Additional work and testing will need to be performed if sorting by a targeted variable is to be included in a future version of this function, which it SHOULD be.

**CODE EXAMPLES:**
`library(DescTools)`
`data("d.pizza")`
`data("mtcars")`

`mutate_filter(d.pizza, f_arg1 = "area == 'Camden'", rem = "1:4, 15,16", expr = "round(count*price,2)")`
`mutate_filter(mtcars, f_arg1 = "vs == 1", rem = "2:5, 11")`
`mutate_filter(mtcars, f_arg1 = "mpg > 20", rem = "11")`

**Comment by oobianom** [comment]
Thanks Brice!

**Comment by brichard1638** [comment]
When are you planning on publishing the next version of quickcode?
________________________________
