### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#34]
I think after the next version release of quickcode on CRAN is complete, I will be developing my own offline R package of unique functions. I will still continue to collaborate with you on quickcode, but I need a process model that has a quick turnaround in terms of function development.

I have at least another 10 functions that are NOT found on CRAN waiting to be developed, and they are being delayed because POSIT or whatever the new name is for R staff can't get a package out in a reasonable amount of time. I do not want to be waiting for the better part of a week for an R package to be published.

I have a global R monitoring tool that relies on new and innovative next-generation functions and it's all being delayed because of this CRAN publishing issue. That is quite irritating to say the least. As far as CRAN not allowing the get_active_conn function to be published, the R package netstat has the same damn functions just disaggregated into two separate nonproductive functions that I combined. So, unless the rules have changed, and I'm guessing they have, those functions passed the CRAN test but an all-inclusive MUCH more productive function doesn't?

This is one of the primary reasons I will be moving to develop my own OFFLINE R package as it will improve my productivity and ensure that the turnaround time for package development solely rests on my efforts.

In any event, it has been a wonderful experience collaborating with you. Stay focused and continue to develop quickcode - it is an amazing package with a lot of future potential. -BR

**Comment by oobianom** [comment]
Thanks for the message, Brice. It's been wonderful collaborating with you as well. No worries, for v1.0, we will try to find ways to include all those functions we missed in v0.9. Wishing you well in the next adventure developing R packages!

I understand your frustration, and many people have said similar things. But I am guessing the publishers of the CRAN packages are either underpaid or volunteer to work on the R project. I simply just wait because they eventually respond and publish the package. 

The biggest downside to developing a package without the intention of putting it in CRAN is that not many people will want to download and use your R package from other sources. CRAN (and bioconductor) are highly trusted by the R community.

Anyway, I will be taking a break after we push out v1.0 in order to write a web book for the quickcode R package. I will be focused on trying to make people more aware of the package, to increase its usage and acceptance by the R community, so I may not be releasing v1.1 until a couple months later.

**Comment by brichard1638** [comment]
Thank you for providing the update.

In terms of the downside to which you suggested in developing a non-public facing package, that doesn't concern me. I'm really not interested in sharing the functions I will be developing anyway.

It actually creates an increased value proposition in my opinion. This is because if I consult with a company in the future and develop functionality that only I have access to (i.e. customized R package), I can charge more per hour for consulting to build advanced applications using data and predictive analytics using R.

________________________________
