### ISSUE TITLE
New Function Proposal: Download One or More Random Images from the Internet

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#4]
The idea for this function is to generate a programmatic capability that can be used to download one or more random images from the internet. Using the www.unsplash.com website, provide a one-step function to achieve this objective.

Proposed Function Name & Structure: genImage(fp = "~/images"), cat = "nature", cnt = 1)

fp = File path and name of the directory to which the image(s) will be stored
cat = The general category comprising the image type (see NOTE4 below)
cnt = The total number of images to generate

NOTE1: An additional argument could be provided called ext that determines which image type extension to generate, For example, ext = "jpg" or ext = "png", etc. Extra code may be required to implement this functionality. The default image extension should be .jpg.

NOTE2: File size can also be added as an argument called size, or independently as two separate arguments called len and wid. Values would programmatically replace those passed in the url argument of the download.file function.

The following code is designed to provide a framework for a functional conversion:

ACQUIRE ONE RANDOM IMAGE FILE
The first step is to download a random image to a pre-established folder in the MyDocuments folder called 'images:'
`dir.create(path = "~/images")`
`download.file(url = "https://source.unsplash.com/random/800x800/?nature&1", destfile = "~/images/img1.jpg", mode = 'wb')`

The ~/ character combination represents an abbreviated file path to a user's My Documents folder. Any file path to which a sub-folder reference is made deeper than the My Documents folder must be manually included in the file path string.

ACQUIRE MULTIPLE RANDOM IMAGE FILES
To download a user-selected number of random image files (in this example 10), apply the following code:
`library(wakefield)`
`for(i in 1:10) {`
`download.file(url = paste0("https://source.unsplash.com/random/500x500/?nature&", i), destfile = paste0("~/images/", string(1, length = 5), ".jpg"), mode = 'wb')`
`Sys.sleep(1) }`

NOTE1: In the code above, (10) random images are downloaded and saved to a sub-folder called 'images.' There should be a limit allowed in the code to prevent the user from crashing R. A good image-generating limit is 50.

NOTE2: The image file size can be easily modified by changing the numeric value references contained in the url.

NOTE3: It is possible that one or more images will be duplicated. The Sys.sleep function reduces this possibility by decelerating the speed at which the code executes. This minimizes the prospect of downloading a duplicate image. If the R code executes too fast, images will be duplicated as the algorithm executes before the website can regenerate a new image. Irrespective of how slow the algorithm executes, it is still possible to download duplicate images. The Sys.sleep function only reduces the probability of duplicate image generation, but does not prevent it from occurring.

NOTE4: Key words used to generate images can be found at the top of the www.unsplash.com page. These key words can be used to replace the 'nature' keyword provided in the download.file function. However, it should be noted that the images returned are inconsistent and do not always match the key word provided. Consequently, the key word that returns the most consistently applicable images is 'nature.'

**Comment by oobianom** [comment]
Brice, I have created this function genImage(). When you have chance, test it out.

Couple things:

CRAN does not support making modifications to the user's file system, so I have tried to minimize this as well as I could by not including the "dir.create" function. Hopefully our function will still pass as it is.

I have implemented everything else as you indicated. One concern is the function name, I am thinking we may need to change it to something a bit more descriptive for R users while making it short too. We can think more on this. 

Finally, I have tried a solution for duplication by using checksum instead of 'Sys.sleep'. This implementation, based on my preliminary test, gets rid of all duplications. You can also verify in your test.

**Comment by brichard1638** [comment]
Obi:::

:::Upon notification, I will continue to test the functions you have created:::🤗

Basic testing of the genImage function is complete.  The following remarks from the testing process are provided:

TESTING RESULTS:

  *   In terms of functional execution, the genImage function runs end-to-end without error, when the appropriate arguments such as fp, cat, ext, and n are correctly passed
  *   However, when the n argument was set to 100, the genImage function ran iteratively without ending, producing an infinite loop; during execution, when the target folder where the images were to be stored was viewed, a single file was continuously being overwritten; only one file was being processed; the algorithm did NOT pass this test
  *   Various values for n were tested; any value less than 100 produced expected results
  *   When multiple function actions were executed where n was a different value, the algorithm ran as expected, providing correct results; this test consisted of a first run where n = 3, then using the same file path location, the algorithm was executed again where n = 50; the first 3 files were overwritten as expected; the total number of files stored post-execution was 50 - this was expected behavior and the function passed this test
  *   A test was conducted to check for duplicate images; upon several executions of the function, the genImage passed the duplicate image test

POST COMMENTS:

  *   Applying the checksum was a great decision call! It is superior to the Sys.sleep function
  *   I believe that the function name genImage is appropriate for this function; however, if you believe the function should be called by a different name, I encourage you to select whatever name you think is appropriate; if you have to change the name, perhaps a name like genRandImg would be more descriptive for generate random image
  *   A decision should be made to determine the maximum value of n. Given that the algorithm failed the test where n > 99, perhaps that value should be the cutoff. If this value were to be the cutoff value, no changes in the current function would be required; if n > 99 is accepted, functional modifications will be required; the question is, what is, or should be the maximum value for n?
  *   With regard to the file path location in the documentation that should be used, the current default of "~/" is fine but it is strongly recommend that the documentation be changed to pass tempdir() as the argument value for fp; RStudio creates a new temp directory for each session; when RStudio is closed, the temp directory along with any files therein contained are automatically removed
  *   The genImage function is not making any changes to the file system, it's simply passing a folder path location where the files will be stored; it is believed that the current structure of the function will pass CRAN requirements
  *   A focus on better documentation should be considered; the current documentation for the genImage function is significantly limited; more focused documentation will improve the appeal and usefulness of the function; areas for documentation improvement include the following:
        *   Alerting the user to the maximum value allowed for n (if a max value has been determined)
        *   A brief summary and listing of possible category keywords acceptable for passing to the cat argument
        *   A reference in the documentation to the website used for image extraction (https://source.unsplash.com)



________________________________

**Comment by oobianom** [comment]
Thanks Brice. Again, a very comprehensive test of the draft function.

I agree with your suggestion of a maximum n of 99. I have refined the function to check for n within 99. If it exceed 99, the function sets n = 99, leaves a warning and continues the process. 

With regards to the function name, I like genRandImg as it's a bit more descriptive. I have updated the function name.

I agree with using tempdir() instead of "~/". I have made the update. And on that note, I agree that the documentation should be a bit more comprehensive. I will work on that, making sure to incorporate your suggestions above.

Finally, the more I think about this function and from reading your comments above, wouldn't it be a nice idea to add the image category in the file name downloaded as well. Doing this will avoid overwriting files from various categories with a particular folder. This also allows one to sort files later on. Additionally, should the file name also be unique even within a particular category? Here is a reason -  say I'd like to download 990 random images, this means that I have to call the function  10 times. However, in the current form of the function, I would need to create 10 different folders to store the files to avoid overwriting. Making unique names will solve that issue. This can be accomplished by including an "overwrite =TRUE/FALSE" argument that allows the user to choose if to overwrite previous files or to create unique names. 

Let me know if you agree with the proposed additionally features to include in this function.

**Comment by brichard1638** [comment]
Obi:::

There are actually a couple of ways that your inquiry can be handled within the genRandImg function. I will provide a brief summary of the options as I understand them to be, based on y our last email correspondence:

OPTION 1

  *   Include the category name as part of the file name, but make the file name unique. This can be achieved by using the string function found in the wakefield package. Pseudo code is provided below:

           library(wakefield)
           paste0("~/images/", "nature_", string(1, length = 5), ".jpg")
           [1] "~/images/nature_fSr4b.jpg"

The result produces a file name called 'nature_fSrJb.jpg' where the category is "nature." The string function generates a unique file name each time it is executed. Returning a combination of both numeric values and letters, the odds of a string value being replicated are slim. The md5sum function can be used to ensure file uniqueness. If there remains a continued concern of file name replication, change the length arg to say 7 or 8.

For this option, no file overwrite option is provided. By default, all file names are unique.

Since the topic of dependencies has been recommended here, let me ask you a question. What is your position on the introduction of dependencies in the quickcode package? The reason for the inquiry is that I need to know whether or not in the future to recommend functions where dependencies are most likely to exist. I am of the belief that while dependencies in R packages should be limited, they should not be eliminated from being included in a particular package. In fact, many of the packages in R that contain some of the most compelling functions are as a result of introducing dependencies from other packages. However, I believe dependencies should be used sparingly and with discretion.

What are your thoughts on this matter?

OPTION 2

  *   As you suggested in your last email, you can provide an overwrite argument that allows the user to select whether or not to overwrite the files in question. I am not a fan of this option as I cannot imagine a circumstance where a user would want to use this particular function to overwrite existing image files. The original intent in using the genRandImg function is to download unique image files. I believe the responsibility here should be on the user to manage files in a way that facilitates the optimal use case for genRandImg. My recommendation would be not to include an overwrite option in this function.
  *   Avoiding an overwrite arg will make the function easier to construct and manage.

Brice

________________________________

**Comment by oobianom** [comment]
I agree with your suggestion in OPTION 2 not to implement the 'overwrite' arg. Instead, I will stick with your first option.

With regards to introducing dependencies, I try as much as possible to avoid it. My biggest reason is that depending on other packages means that if something goes wrong in that package, mine is affected. Nonetheless, I still include dependencies if they are absolutely needed. If I have to use multiple functions from a package, I think its worth it to depend on that package. If I only have to use one or two functions, then the next question I ask is if I can replace or recreate those particular functionality. If not, then I add dependency to the package. 

So for your suggestion of unique names, I am leaning more towards your idea of using the checksum instead of using the wakefield package. 

This is not to say that you should not suggest functionalities that may depend on other packages in the future. As I mentioned, if its absolutely needed, we will add dependencies to other packages if there is no other alternative.

**Comment by brichard1638** [comment]
Obi:::

Fair enough. I will be sensitive to the recommended use of dependencies when I provide ideas for future functions.

I do think though, that to have a really compelling package will require, at some point, the use of dependencies in your package. Consequently, there are plenty of R packages that exist that can be used to manage dependencies.

Also, due to the egregious amount of duplication that exists in functional capabilities in R, there will be other functions from other packages that can be used if, for example, a dependency in a called package is no longer available.

For example, let's say that the md5sum function in the tools package is removed for whatever reason. There is actually a much more extended function called hashfiles found in the easyr package that could be used as a very nice replacement. It provides the same functionality as md5sum but with extended capabilities.

There is one more thought you should consider regarding the concept of including dependencies in your package. Some packages are more robust in terms of their staying power and existence as a package than others. For example, a miscellaneous package of functions called 'berryFunctions' is most likely not going to fundamentally change in terms of removed or modified existing functions. This package has been in the R environment since 9-Jun-2014. It currently contains 197 pages of functions. In terms of dependencies, I would certainly be inclined to trust this dependency package over other newer, untested miscellaneous packages in terms of time.

In fact, now that we are discussing the issue of dependencies, in the future, when I recommend a dependency, I will provide supporting information as to why I think that dependency should be used. Supporting information such as the total number of versions the dependency has had, the number of days since its last update, and its original release date are examples.

As long as you are thoughtful in terms of considering which dependency packages to use, I think you should be fine. Not all R packages are created equally in terms of reliability. However, that should not prevent you from using them. There are plenty of workarounds for any dependency package that is used.

Finally, if needed, I am certainly a resource who is willing to help you manage this effort. For example, once quickcode becomes sufficiently large in terms of the number of functions it contains, you might want to write an R script that compiles a listing of all the functions that contain dependencies. This list can be used to monitor the impact that any dependency will have on that function.

Keep in mind, I developed an application I call "PEGUSYS" that I use to monitor the most compelling packages and functions in all of R. I am actively monitoring almost 2,000 functions across 363 R packages, including their dependencies. So, I wouldn't worry about what impact a dependency will have on your quickcode package. I have insights into R that no one else has.

Brice
________________________________

**Comment by oobianom** [comment]
Great insight there, Brice. Points well noted. It's great to hear that you can actually help with this aspect. And yes, I agree that dependencies are needed. Actually the package currently depends on some packages. No to worry, we will include more as we improve this package.
