### ISSUE TITLE
Identify Whether an R Package has Been Decommissioned

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#8]
This function proposes to return either a TRUE or FALSE value based on whether a passed package name is either active or decommissioned. The proposed name for this function is rdecomPkg.

The skeleton code logic proposed for this function is provided as follows:
`library(stringr)`
`url = "https://cran.r-project.org/web/packages/pkg/index.html"`
`html_Content = readLines(url)`
`txt = unlist(str_extract_all(html_Content, pattern = "was removed from the CRAN repository"))`
`ifelse(length(txt) == 1, TRUE, FALSE)`

NOTE: The pkg name used in the url scaler is dynamic. It extracts the pkg name passed to the rdecomPkg function's pkg argument.

Function structure:  rdecomPkg(pkg)

A TRUE value returned means that the package name passed has been decommissioned; a FALSE value means the package remains active on CRAN.

The function contains a single argument called **pkg**.

Code Example:
`rdecomPkg("cattonum")`
[1] TRUE

**Comment by oobianom** [comment]
This is a great addition to the archivedPkg() that we recently to quickcode!

I am okay with the function name. However, I'd prefer for the argument to be "package" instead of "pkg"

I will work on an initial draft for this function. 

The more I think about it, we may even expand the functionality later on. Like, we could provided the user with results of 
the date when the package was decommissioned and also the version at which it was decommissioned. More so, I would think that if a user is querying a commissioned package, the next step is probably to see if they can download the last version prior to the package being decommissioned. So with regards to that last portion, we may also provide them with the link to download the last version. Let me know what you think of these ideas to expand the functionality. Again, we don't have to incorporate them yet, but maybe in future releases.

**Comment by brichard1638** [comment]
Obi:::

I had a lot of thoughts regarding the improved functionality for this function but I initially withheld my ideas because I didn't know how open you would be to a more comprehensive review of this capability.

There are certainly many different ways this functionality can be developed. If you are interested in a much deeper exploration of this function, including the ideas you have suggested, let me know, and I will start laying out a set of proposals supporting future functionality.

Brice
________________________________

**Comment by oobianom** [comment]
Yes, that would be great. Let's improve it further.

**Comment by brichard1638** [comment]
Obi:::

I've been really busy lately with some deep research on which I have been recently funded. We might have to table this until after the next version of quickcode is released.

I don't want to hold you up in terms of you continued work on your package.

I would like to take some time to think about how to structure these ideas before sharing them with you.

I need to review this concept more deeply before responding.

😃

Brice
________________________________

**Comment by oobianom** [comment]
Congrats on your funding, Brice! I agree, no need to rush. Take your time, we can always expand the functionality in future releases. In the meantime, we in just have the new version include your initial ideas above. Also quite busy at my day job, so don't think we can publish a new version until sometime in December.

**Comment by brichard1638** [comment]
Obi:::

Thank you! I also have a few ideas percolating on a very interesting function that as far as I know, does not exist in R which one would think would in fact exist.

I will share this idea with you in the coming days.

Brice
________________________________

**Comment by oobianom** [comment]
This function is all set for the initial release. We can work on add more functionality to it in later versions as time permit.
